---
title: "Replication of Study 2 by Walsh & Sloman (2004)"
author: |
  | Erin Bennett
  | `erindb@stanford.edu`
output:
  pdf_document:
    toc: false
    highlight: zenburn
    toc_depth: 3
---

# Introduction

This study is about how people revise their beliefs when they are presented with a counterexample to a causal relationship.

There are a few questions:

1. **Are other effects screened off from the effect in the counterexample, given that the cause happened?** That is, do people update their beliefs about that particular causal relationship in isolation, without influencing other parts of their theory? Or do they update their theory in a more complex way such that in this and other counterexamples, other things that usually result from the cause are also less likely? E.g. "My new neighbors tell me they are in a fraternity. I think they will have loud parties late at night and their apartment will be messy. If after a few weekends, the apartment is always really quiet, my expectation might be less strong that it's messy."

    Walsh & Sloman found that effects are not screened off and that the counterexample results in people expecting other possible consequents less.
    
    *Comparison 1:* For "A causes B" and "A causes C", ask participants about two situations:
    
    1) A is true. How likely is C?
    
    2) A is true and B is false. How likely is C? 
    
    If B and C are screened off from one another given A, then both questions should have the same answer. If participants are revising their theories in a more comples way, they might be different. In fact, the answer for 2 tends to be lower than the answer for 1.

<!-- 2. **Are other effects screened off, given that people's explanation of the counterexample doesn't hold?** That is, do people revise their beliefs by hypothesizing one explanation for the counterexample (the cause doesn't really hold, something happened to prevent the effect, some necessary condition wasn't met, etc.) and using that explanation to make new predictions? E.g. "Maybe they're in a really nerdy fraternity. If another fraternity replaces them that isn't nerdy, the new fraternity will probably have loud parties and messy apartments."

    Walsh & Sloman found that other effects *are* screened off given the cause is true *and* the explanation the participant generated for the counterexample is false.
    
    *Comparison 2:* Ask participants about two situations:
    
    1) A is true and B is false.
        a. Why do you think that is?
        b. Also, how likely is C?
        
    2) A is true and whatever explanation you gave for the situation in 1 is true. How likely is C?
    
    If B and C are screened off from one another given the explanation for the counterexample, then both questions should have the same answer. In fact, they do. -->

2. **Do people revise their causal believes in the face of a counterexamples?** That is, are these exceptions, conditions, etc. already known and accounted for and participants just have enough evidence for them when they see the counterexample? Or are they adding them in as needed? E.g. "If a new fraternity replaces my neighbors that may or may not be nerdy (I just don't know), then will my experience with my quiet neighbors influence my expectations about the new fraternity?"

    Walsh & Sloman found that people have report different probabilities of effects given causes for (almost) the same question after the counterexample.

    *Comparison 2:* Ask participants about P(C|A) before and after the counterexample.
    
    1) A is true. How likely is C?
        
    2) A is true and you don't know whether that explanation you gave for the counterexample situation is true. How likely is C?
    
    If beliefs are not revised, you would expect no difference between these responses, because 2 has no more information than 1 (literally, at least). But in fact, responses to these questions tend to be different.

# Methods

## Power analysis

Original N=20.
Planned N=20.

```{r, echo=F, warning=F, message=F}
library(tidyr)
library(dplyr)
library(pwr)
orig.d = data.frame(
  question = c('B|A', 'B|A and not C', 'B|A and explanation unknown', 'B|A and explanation absent', 'B|A and explanation present'),
  qnum = c(0, 2, 3, 4, 5),
  prob = c(0.85, 0.63, 0.71, 0.85, 0.62),
  n = 20
)
orig.rs = data.frame(
  comparison = c(1,2,3),
  qnA = c(0, 2, 0),
  qnB = c(2, 5, 3),
  questions = c('q0>q2', 'q2~q5', 'q0>q3'),
  tvalue = c(5.03, 0.60, 5.37),
  n = 20
) %>% mutate(df = n-1,
             p = pt(tvalue, df),
             es = tvalue/sqrt(n))
orig.rs$power = mapply(function(n, d) {return(pwr.t.test(n=n, d=d, sig.level=0.05, type='paired')$power)}, orig.rs$n, orig.rs$es)
orig.rs$expectedES = mapply(function(n, power) {return(pwr.t.test(n=n, power=power, sig.level=0.05, type='paired')$d)}, orig.rs$n, orig.rs$power)
```

Effect size for the first comparison -- P(B|A) versus P(B|A and not C) -- was 1.12, so with the same sample size the power will be 0.999.

Effect size for the second comparison -- P(B|A) versus P(B|A and explanation unknown) -- was 1.20, so with the same sample size the power will be 0.999.

## Planned sample

English-speaking participants on Amazon's Mechanical Turk.

## Materials

Walsh & Sloman (2004) report using 6 different stories. Two are used as examples in their 2004 paper. <!-- Two more are used as an example in a 2008 report of the same experiment in a book chapter. -->

Stories:

* Jogging regularly causes a person to lose weight. Jogging regularly causes a person to increase their fitness level.
* Worrying causes difficulty in concentrating. Worrying causes insomnia.
<!-- * Following this diet causes you to have a good supply of iron. Following this diet causes you to lose weight.
* Playing loud music in Paul’s apartment causes the neighbors on his left to complain. Playing loud music in Paul’s apartment causes the neighbors on his right to increase the volume on their TV. -->

These stories were (I think) designed such that the effects would not directly affect one another, though I'm not sure they succeeded. I created seven more items with this intended causes structure.

* Drinking coffee causes a person to stay up late. Drinking coffee causes a person to be more focused.
* Going to the beach on a sunny day causes a person to get a suntan. Going to the beach on a sunny day causes a person to see surfers.
* Reading for a very long stretch of time causes a person to get a headache. Reading for a very long stretch of time causes a person's vocabulary to increase.
* Joining a cooking meetup group causes a person to make friends. Joining a cooking meetup group causes a person to get better at cooking.
* Taking a painting class causes a person to get paint on their clothes. Taking a painting class causes a person to improve their painting skills.
* Practicing guitar a lot causes a person to start writing their own songs. Practicing guitar a lot causes a person's fingers to get calloused.
* Flying from the US to Japan causes a person to experience jetlag. Flying from the US to Japan causes a person to hear more Japanese.

## Procedure

Each participant sees each story. Stories are presented one at a time, in blocks.

In each block, first the causal statements in question are presented. These will be visible for rest of the block. Then the following questions are asked (in order):

1) A is true. How likely is C?

2) A is true and B is false.
    a. Why do you think that is?
    b. Also, how likely is C?
    
3) A is true and you don't know whether *[the explanation you gave for 2a]* is true. How likely is C?

4) A is true and *[the explanation you gave for 2a]* is false. How likely is C?

5) A is true and *[the explanation you gave for 2a]* is true. How likely is C?

## Analysis plan

Run t-tests to see whether the following replicate:

* *Comparison 1:* $Answer2a < Answer1$
* *Comparison 2:* $Answer1 \neq Answer3$

## Differences from original study

The sample population of the original study was a group of college students. My sample will be participants on Amazon's Mechanical Turk. Both groups probably reason similarly about causes. However, it is possible that workers on Mechanical Turk will be more concerned about giving consistent answers than college students, so for similarly phrased answers we might expect a slight bias for this new population giving the same answer.

The setting will be online rather than in a lab, which means that participants might be paying less attention, or take breaks in the middle of the study. I don't anticipate that having a strong effect on the results, since these questions don't seem to require a lot of concentration.

<!-- attention checks!!! -->

I will use some basic natural language processing to repeat back participants' explanations with (hopefully) appropriate syntax. The original study used a human to do this task. Because doing this with a computer is more error-prone, I will have to ask the question in a slightly different way, giving participants a particular syntactic frame to fill in. The resulting program might respond to people with nonsense. It might be good if I could give participants an option to tell me whether the question I'm asking is nonsense so that I can exclude that data.

# Methos Addendum

## Actual sample

## Differences from pre-date collection methods plan

# Results

## Data preparation

## Confirmatory analysis

## Exploratory analyses

# Discussion

## Summary of replication attempt

## Commentary